### ISSUE TITLE
Error thrown when submitting array instead of group id

### ISSUE THREAD

**Issue by fabienmazieres** [altaris/seat-navy-issue#1]
Hi,

I provided by mistake an array instead of an int as I am lagging behind in the code. I got a very nasty error message so I think you need extra variable checks

I called /group/{\'group_id\': \'5ef5a7b63d6470a85cc575cf\', \'group_name\': \'superusers\'}

ERROR 500
['Traceback (most recent call last):\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__\n await self.app(scope, receive, _send)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__\n raise exc from None\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__\n await self.app(scope, receive, sender)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__\n await route.handle(scope, receive, send)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle\n await self.app(scope, receive, send)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/starlette/routing.py", line 41, in app\n response = await func(request)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/fastapi/routing.py", line 198, in app\n raw_response = await run_endpoint_function(\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/fastapi/routing.py", line 151, in run_endpoint_function\n return await run_in_threadpool(dependant.call, **values)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool\n return await loop.run_in_executor(None, func, *args)\n', ' File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run\n result = self.fn(*self.args, **self.kwargs)\n', ' File "/usr/src/app/sni/api/group.py", line 129, in get_group_name\n return group_record_to_response(group.Group.objects(pk=group_id).get())\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 260, in get\n result = next(queryset)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1590, in __next__\n raw_doc = next(self._cursor)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1666, in _cursor\n self._cursor_obj = self._collection.find(self._query, **self._cursor_args)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1715, in _query\n self._mongo_query = self._query_obj.to_query(self._document)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/queryset/visitor.py", line 90, in to_query\n query = query.accept(QueryCompilerVisitor(document))\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/queryset/visitor.py", line 185, in accept\n return visitor.visit_query(self)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/queryset/visitor.py", line 79, in visit_query\n return transform.query(self.document, **query.query)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/queryset/transform.py", line 120, in query\n value = field.prepare_query_value(op, value)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/base/fields.py", line 513, in prepare_query_value\n return self.to_mongo(value)\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/base/fields.py", line 509, in to_mongo\n self.error(str(e))\n', ' File "/usr/src/app/.virtualenv/lib/python3.8/site-packages/mongoengine/base/fields.py", line 171, in error\n raise ValidationError(message, errors=errors, field_name=field_name)\n', 'mongoengine.errors.ValidationError: "{\'group_id\': \'5ef5a7b63d6470a85cc575cf\', \'group_name\': \'superusers\'}" is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string\n']

**Comment by fabienmazieres** [comment]
working as expected

**Comment by altaris** [comment]
Yep, you cannot pass a dict in string form like that; and this method doesn't expect a dict argument anyway. You received the trace because the test instance is in debug mode. Otherwise, the `500` error is expected.
